### ISSUE TITLE
Не совсем понятно: деньги зачисляются и на счёт клиента, и в банкомат?

### ISSUE THREAD

**Issue by coursar** [Zalyalov-Almaz/ATM#7]
https://github.com/Zalyalov-Almaz/ATM/blob/8435a3d81479c282e84a3b70159fa3132cff9d78/src/atm/ATM.java#L32

**Comment by Zalyalov-Almaz** [comment]
в банкомате же на эту сумму больше становится, а след строкой на счет клиента
